name: Jonathan E. Chen
description: "A Journal on Design, Technology, and Life"
url: http://wikichen.is
author:
  name: Jonathan E. Chen
  email: hello@wikichen.is

markdown: kramdown

pygments: true

permalink: /:categories/:title/

cdn_baseurl: http://cloud.wikichen.is
cdn_url: http://cloud.wikichen.is/serving

enable_disqus: false

exclude: ['node_modules', 'gemfile', 'gulpfile.js', 'Rakefile',
          's3_website.yml', 'README.md', 'LICENSE']
