name: "(wikichen's web wonderland)"
description: "a SHOW &amp; TELL on design, technology, and life"
url: http://wikichen.is
author:
  name: Jonathan E. Chen
  email: hello@wikichen.is

markdown: kramdown
pygments: true
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
permalink: /:categories/:title

enable_disqus: true
cdn_baseurl: http://cloud.wikichen.is/
cdn_url: http://cloud.wikichen.is/serving/

assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/stylesheets
    - _assets/javascripts
    - _assets/images
